services:
    terminal42_oembed.listener.twitter_element:
        class: Terminal42\OEmbedBundle\EventListener\DataContainer\TwitterElementListener
        arguments:
            - '@database_connection'
            - '@logger'
        tags:
            - { name: contao.callback, table: tl_content, target: config.onsubmit }
            - { name: contao.callback, table: tl_content, target: fields.twitter_url.save }

    terminal42_oembed.controller.tweet:
        class: Terminal42\OEmbedBundle\Controller\OEmbedController
        tags:
            - { name: contao.content_element, type: embedded_tweet, category: twitter }

    terminal42_oembed.controller.user_timline:
        class: Terminal42\OEmbedBundle\Controller\OEmbedController
        tags:
            - { name: contao.content_element, type: user_timline, category: twitter }
