services:
    terminal42_twitter.data_container.content:
        class: Terminal42\OEmbedBundle\DataContainer\ContentDataContainer
        public: true
        arguments:
            - "@database_connection"
            - "@logger"
